actionid: root
msg: installpkg
cmdargs: ['C:\\Users\\Ciaran\\Documents\\PyCoTools\\.tox\\root\\Scripts\\pip.EXE', 'install', 'C:\\Users\\Ciaran\\Documents\\PyCoTools\\.tox\\dist\\PyCoTools-3.4.3.zip']
env: {'TMP': 'C:\\Users\\Ciaran\\AppData\\Local\\Temp', 'COMPUTERNAME': 'CIARAN', 'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'USERDOMAIN': 'CIARAN', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\PowerShell\\ResourceManager\\AzureResourceManager\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\PowerShell\\ServiceManagement\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\PowerShell\\Storage\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\PowerShell\\Modules\\;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\platform\\PowerShell', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '4501', 'PATH': 'C:\\Users\\Ciaran\\Documents\\PyCoTools\\.tox\\root\\Scripts;c:\\anaconda2\\Library\\bin;C:\\Anaconda2;C:\\Anaconda2\\Library\\mingw-w64\\bin;C:\\Anaconda2\\Library\\usr\\bin;C:\\Anaconda2\\Library\\bin;C:\\Anaconda2\\Scripts;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Microsoft MPI\\Bin\\;C:\\Perl64\\site\\bin;C:\\Perl64\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Program Files\\copasi.org\\COPASI 4.19.140\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Anaconda2;C:\\Anaconda2\\Scripts;C:\\Anaconda2\\Library\\bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Anaconda3;C:\\Program Files\\Anaconda3\\Scripts;C:\\Program Files\\Anaconda3\\Library\\bin;C:\\Users\\Ciaran\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft\\Web Platform Installer\\;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\wbin;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\E-Cell\\bin;C:\\ProgramData\\Miniconda2;C:\\ProgramData\\Miniconda2\\Scripts;C:\\ProgramData\\Miniconda2\\Library\\bin;C:\\Program Files\\PuTTY\\;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Users\\Ciaran\\AppData\\Local\\Microsoft\\WindowsApps;C:\\ffmpeg\\bin;', 'SYSTEMROOT': 'C:\\WINDOWS', 'MSMPI_BIN': 'C:\\Program Files\\Microsoft MPI\\Bin\\', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'VIRTUAL_ENV': 'C:\\Users\\Ciaran\\Documents\\PyCoTools\\.tox\\root', 'TEMP': 'C:\\Users\\Ciaran\\AppData\\Local\\Temp', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROGRAMDATA': 'C:\\ProgramData', 'CONDA_PREFIX': 'C:\\Anaconda2', 'CONDA_PS1_BACKUP': '$P$G', 'PYTHONHASHSEED': '175', 'CONDA_DEFAULT_ENV': 'root', 'HOMEPATH': '\\Users\\Ciaran', 'USERDOMAIN_ROAMINGPROFILE': 'CIARAN', 'PROGRAMW6432': 'C:\\Program Files', 'USERNAME': 'Ciaran', 'LOGONSERVER': '\\\\CIARAN', 'PROMPT': '(root) $P$G', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'LOCALAPPDATA': 'C:\\Users\\Ciaran\\AppData\\Local', 'ONEDRIVE': 'C:\\Users\\Ciaran\\OneDrive', 'COPASIDIR': 'C:\\Program Files\\copasi.org\\COPASI 4.19.140', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'SESSIONNAME': 'Console', 'WINDIR': 'C:\\WINDOWS', 'HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\Ciaran\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '4', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C:\\Users\\Ciaran'}

Processing c:\users\ciaran\documents\pycotools\.tox\dist\pycotools-3.4.3.zip
Collecting pandas (from PyCoTools==3.4.3)
  Downloading pandas-0.20.2-cp27-cp27m-win_amd64.whl (8.3MB)
Collecting numpy (from PyCoTools==3.4.3)
  Downloading numpy-1.13.0-cp27-none-win_amd64.whl (7.6MB)
Collecting scipy (from PyCoTools==3.4.3)
  Downloading scipy-0.19.0.zip (15.3MB)
Exception:
Traceback (most recent call last):
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\anaconda2\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\anaconda2\Lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\ciaran\documents\pycotools\.tox\root\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\ciaran\\appdata\\local\\temp\\pip-build-p90y5i\\scipy'
