DEBUG:pycotools.tasks:tasks:run_parallel:602:running Model(name=Michaelis-Menten, time_unit=s, volume_unit=ml, quantity_unit=mmol)
DEBUG:pycotools.tasks:tasks:run_parallel:602:running Model(name=Michaelis-Menten, time_unit=s, volume_unit=ml, quantity_unit=mmol)
DEBUG:pycotools.tasks:tasks:run_parallel:602:running Model(name=Michaelis-Menten, time_unit=s, volume_unit=ml, quantity_unit=mmol)
DEBUG:pycotools.viz:viz:parse_experimental_files:1390:tpe self.cls parse --> MultiParameterEstimation(copy_number="3", pe_number="20", method="genetic_algorithm_sr")
INFO:pycotools.viz:viz:plot:1517:Plotting "E"
INFO:pycotools.viz:viz:plot:1517:Plotting "ES"
INFO:pycotools.viz:viz:plot:1517:Plotting "P"
INFO:pycotools.viz:viz:plot:1517:Plotting "S"
INFO:pycotools.tasks:tasks:run_analysis:4866:running /home/b3053674/Documents/Models/2018/01_Jan/PyCoToolsQuickStart/ProfileLikelihoods/0/(S bind E).kf.cps
INFO:pycotools.tasks:tasks:run_analysis:4866:running /home/b3053674/Documents/Models/2018/01_Jan/PyCoToolsQuickStart/ProfileLikelihoods/0/(ES produce P).kcat.cps
INFO:pycotools.tasks:tasks:run_analysis:4866:running /home/b3053674/Documents/Models/2018/01_Jan/PyCoToolsQuickStart/ProfileLikelihoods/0/(S unbind E).kb.cps
ERROR:root:ultratb:format_record:982:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 8))

ERROR:root:ultratb:format_record:982:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 8))

ERROR:root:ultratb:format_record:982:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 8))

ERROR:root:ultratb:format_record:982:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 8))

ERROR:root:ultratb:format_record:982:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 8))

ERROR:root:ultratb:format_record:982:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 8))

INFO:pycotools.tasks:tasks:run:3740:running model: 0
INFO:pycotools.tasks:tasks:run:3740:running model: 1
INFO:pycotools.tasks:tasks:run:3740:running model: 2
INFO:pycotools.tasks:tasks:run:3740:running model: 0
INFO:pycotools.tasks:tasks:run:3740:running model: 1
INFO:pycotools.tasks:tasks:run:3740:running model: 2
INFO:pycotools.tasks:tasks:run:3740:running model: 0
INFO:pycotools.tasks:tasks:run:3740:running model: 1
INFO:pycotools.tasks:tasks:run:3740:running model: 2
INFO:pycotools.tasks:tasks:run:3740:running model: 0
INFO:pycotools.tasks:tasks:run:3740:running model: 1
INFO:pycotools.tasks:tasks:run:3740:running model: 2
INFO:pycotools.tasks:tasks:run:3740:running model: 0
INFO:pycotools.tasks:tasks:run:3740:running model: 1
INFO:pycotools.tasks:tasks:run:3740:running model: 2
INFO:pycotools.viz:viz:plot:1540:Plotting "kb"
INFO:pycotools.viz:viz:plot:1540:Plotting "E"
INFO:pycotools.viz:viz:plot:1540:Plotting "kcat"
INFO:pycotools.viz:viz:plot:1540:Plotting "P"
INFO:pycotools.viz:viz:plot:1540:Plotting "S"
INFO:pycotools.viz:viz:plot:1540:Plotting "ES"
INFO:pycotools.viz:viz:plot:1540:Plotting "kf"
INFO:pycotools.viz:viz:plot:1540:Plotting "E"
INFO:pycotools.viz:viz:plot:1540:Plotting "S"
INFO:pycotools.viz:viz:plot:1540:Plotting "ES"
INFO:pycotools.viz:viz:plot:1540:Plotting "P"
INFO:pycotools.viz:viz:plot:2621:Plotting "kb" Vs "kb"
INFO:pycotools.viz:viz:plot:2621:Plotting "kb" Vs "kcat"
INFO:pycotools.viz:viz:plot:2621:Plotting "kb" Vs "kf"
INFO:pycotools.viz:viz:plot:2621:Plotting "kb" Vs "RSS"
INFO:pycotools.viz:viz:plot:2621:Plotting "kb" Vs "k"
INFO:pycotools.viz:viz:plot:2621:Plotting "kb" Vs "kf"
INFO:pycotools.tasks:tasks:run_analysis:4930:running /home/b3053674/Documents/Models/2018/01_Jan/PyCoToolsQuickStart/ProfileLikelihoods/0/kb.cps
INFO:pycotools.tasks:tasks:run_analysis:4930:running /home/b3053674/Documents/Models/2018/01_Jan/PyCoToolsQuickStart/ProfileLikelihoods/0/kcat.cps
INFO:pycotools.tasks:tasks:run_analysis:4930:running /home/b3053674/Documents/Models/2018/01_Jan/PyCoToolsQuickStart/ProfileLikelihoods/0/kf.cps
